import {
  Activity,
  Microscope,
  BookCheck,
  Baby,
  Brain,
  Dna,
  Eye,
  EyeOff,
  FlaskConical,
  Glasses,
  HeartPulse,
  Layers,
  ScanEye,
  Settings2,
  ShieldAlert,
  Syringe,
  Users,
} from 'lucide-react';

export const DOCTOR_MODULES = [
  // {
  //   title: 'Dashboard',
  //   icon: LayoutDashboard,
  //   permission: 'read_adnexa_examination',
  //   route: '/dashboard',
  // },
  {
    title: 'Examinations',
    icon: BookCheck,
    permission: 'read_adnexa_examination',
    route: '/examinations',
  },
  // {
  //   title: 'My Patients',
  //   icon: Activity,
  //   permission: 'read_adnexa_examination',
  //   route: '/glaucoma',
  // },
  // {
  //   title: 'Orders',
  //   icon: Microscope,
  //   permission: 'read_adnexa_examination',
  //   route: '/oculoplasty',
  // },
  {
    title: 'RETINA',
    icon: ScanEye,
    permission: 'read_adnexa_examination',
    route: '/retina',
  },
  {
    title: 'GLAUCOMA',
    icon: Activity,
    permission: 'read_adnexa_examination',
    route: '/glaucoma',
  },
  { title: 'UVEA', icon: EyeOff, permission: 'read_adnexa_examination', route: '/uvea' },
  {
    title: 'PAEDIATRIC OPHTHALMOLOGY',
    icon: Baby,
    permission: 'read_adnexa_examination',
    route: '/paediatric',
  },
  {
    title: 'COMPREHENSIVE OPHTHALMOLOGY',
    icon: Layers,
    permission: 'read_adnexa_examination',
    route: '/comprehensive',
  },
  { title: 'OPHTHALMOLOGY', icon: Eye, permission: 'ophthalmology:access', route: '/eye-smart' },
  {
    title: 'LOW VISION & CSE',
    icon: Glasses,
    permission: 'read_adnexa_examination',
    route: '/low-vision',
  },
  { title: 'REHAB', icon: HeartPulse, permission: 'rehab:access', route: '/rehab' },
  {
    title: 'REFRACTIVE SURGERY',
    icon: Syringe,
    permission: 'read_adnexa_examination',
    route: '/refractive',
  },
  {
    title: 'CATARACT',
    icon: FlaskConical,
    permission: 'read_adnexa_examination',
    route: '/cataract',
  },
  {
    title: 'EMERGENCY',
    icon: ShieldAlert,
    permission: 'read_adnexa_examination',
    route: '/emergency',
  },
  {
    title: 'OCULAR GENETICS',
    icon: Dna,
    permission: 'read_adnexa_examination',
    route: '/genetics',
  },
  {
    title: 'NEURO-OPHTHALMOLOGY',
    icon: Brain,
    permission: 'read_adnexa_examination',
    route: '/neuro',
  },
  {
    title: 'OCULAR PROSTHESIS',
    icon: Settings2,
    permission: 'read_adnexa_examination',
    route: '/prosthesis',
  },
  {
    title: 'ORTHOPTICS',
    icon: Users,
    permission: 'read_adnexa_examination',
    route: '/orthoptics',
  },
  {
    title: 'FELLOW CLINIC',
    icon: Microscope,
    permission: 'read_adnexa_examination',
    route: '/fellow',
  },
  {
    title: 'CALCLINIC FOR UNKNOWN',
    icon: FlaskConical,
    permission: 'read_adnexa_examination',
    route: '/calc-clinic',
  },
  {
    title: 'FIRST VISION',
    icon: Eye,
    permission: 'read_adnexa_examination',
    route: '/first-vision',
  },
] as const;
